spring:
  datasource:
    url: jdbc:mysql://192.168.1.204/temp?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gaiga
    password: ahffkd18!
   
  jpa:
    hibernate:
      ddl-auto: update
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: 
    
    